---
title: "Leaving the Academy: Resources from Open Post Academics"
author: "Beth M. Duckles and OPA Contributors"
site: bookdown::bookdown_site
documentclass: book
output:
  bookdown::gitbook: default
  #bookdown::pdf_book: default
---

# Welcome to Open Post Academics {-} 
This is a set of resources that collected during the [Open Post Academics Mentorship Program](https://openpostac.org/). This program was designed to support people with a PhD who are considering leaving academia. 

The sections in this book were drawn from the notes over a series of eight workshops. Each week focused on one central topic that folks tend to face when they consider moving away from the academy. In the workshop, we heard from speakers, wrestled with the issues and talked about the implication of topics in our own lives.  

Included in this document are some of the resources they shared as well as some of the general comments that were made throughout. I have been intentionally very selective about including comments so as to preserve the confidential discussions we had. 

At the end of this book, you will also find some of the exercises we used and even more resources and materials in the appendices. 

In the program, participants worked with mentors who had already left academia and who spent time talking with them about their goals and future directions. You may see references to that in the text. Additionally, participants created open projects to share their skills and knowledge with the world. You will find examples of these projects on the main website for OPA: https://openpostac.org/.  


## Purpose and Objectives  {-}
Purpose: To empower people with a PhD to share their knowledge and skills more openly.

**Objectives**

- To expand the network of participants to more people outside of academia
- For participants to understand their skill set and how to apply those abilities to projects outside of academia.
- To create a project that shares those skills openly.

**Guiding Principles** 

There are a few orienting beliefs for the OPA program: 

- We assume that people with PhD's know their needs better than anyone else. We trust the participants in the program and the readers of this document make any changes for themselves to make the materials more useful for their needs.
- We created a code of conduct because we believe that everyone in the program should feel safe. This is summarized as: 
*Be respectful, honest, inclusive, accommodating, appreciative, and open to learning from everyone else. Do not attack, demean, disrupt, harass, or threaten others or encourage such behavior.* 
- Mentors and Experts in the OPA program are there to listen, give resources and offer suggestions. It is entirely up to the person who is leaving academia to follow up and to do what makes sense for them. 
- We ask all participants in the program to do an open project. This is a key way for the OPA program to show what participants are capable of. The project should be a minimum viable project that is not overly complex.  

*Appreciation* 
The OPA program and this document owes a great debt of gratitude to the support and leadership of the mentors and participants of the [Mozilla Open Leaders X](https://foundation.mozilla.org/en/opportunity/mozilla-open-leaders/open-leaders-x/) program. 

In particular support and suggestions from [Julia Stewart Lowndes](https://www.mozillapulse.org/profile/1560), [Abigail Cabunoc Mayes](https://www.mozillapulse.org/profile/62) and [Chad Sansing](https://www.mozillapulse.org/profile/58) have been instrumental. Thank you.  

## Contributing {-}

**This is not a perfect document.** We're certainly missing resources and links as well as great articles and books that would be helpful to others with a PhD looking to create a life outside of academia. There are also additional topics we would like to work on for the future. This document is not finished. 

Please help improve this document by sharing resources and materials that have helped you. You can do this by emailing openpostacs@gmail.com. 

We reserve the right to edit for clarity and content. The goal is to ensure that the document makes sense. 

If you are an editor and have time to volunteer for editing this document, we would be very grateful for your support. Please send an email. 


## License  {-}

This work is licensed under a [Creative Commons Attribution International 4.0 License.](https://creativecommons.org/licenses/by/4.0/) 

This means that you are free to share, copy, adapt or remix this material, to use it in places where you think it might be beneficial. 

You must attribute the writing to this project (cite your sources!), you must also link to this license and to indicate if you have made changes. 

Use common sense with what you read here and in the resources we share with you. Everyone is different. What works for me might not work for you. We don't take any responsibility for your choices.  

We would also really appreciate hearing what you do with this if you do end up using it! 


## Authorship {-}
The was written, edited and is maintained by [Beth M. Duckles](https://github.com/bduckles) with help from the OPA particpants, mentors and experts. Opinions are Beth's unless they are in quotes.

Contributors include: 

- Debra Erickson
- Amanda Krauss 
- Marie-Eve Monette
- Gloria Montebruno Saller 
- Sara Schley 
- Susanne Marion Stadlbauer 
- Rachel Reeves
- Rosa Vieira de Alma 
- Wylie Wan
- Miyabi 'Abbie' Yamamoto



